### ISSUE TITLE
test_math failure

### ISSUE THREAD

**Issue by scheung38** [nryoung/algorithms#81]
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/helpers/pycharm/utrunner.py", line 120, in <module>
    modules = [loadSource(a[0])]
  File "/Applications/PyCharm.app/Contents/helpers/pycharm/utrunner.py", line 41, in loadSource
    module = imp.load_source(moduleName, fileName)
  File "/Users/sebc/PycharmProjects/algorithms/algorithms/tests/test_math.py", line 3, in <module>
    from ..math.extended_gcd import extended_gcd
ValueError: Attempted relative import in non-package

Process finished with exit code 1

Any idea?

**Comment by nryoung** [comment]
Without any further info about your environment, this will be impossible to troubleshoot. If, by chance, you are using Python 3.x, then changes are coming soon to this library to support this.

Feel free to open a new issue with more details.
